services:
  web:
    image: ${IMAGE_REGISTRY:-local}/lokso-frontend:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile.web

  space:
    image: ${IMAGE_REGISTRY:-local}/lokso-space:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/space/Dockerfile.space

  admin:
    image: ${IMAGE_REGISTRY:-local}/lokso-admin:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/admin/Dockerfile.admin

  live:
    image: ${IMAGE_REGISTRY:-local}/lokso-live:${APP_RELEASE:-latest}
    build:
      context: ../../
      dockerfile: apps/live/Dockerfile.live

  api:
    image: ${IMAGE_REGISTRY:-local}/lokso-backend:${APP_RELEASE:-latest}
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.api

  proxy:
    image: ${IMAGE_REGISTRY:-local}/lokso-proxy:${APP_RELEASE:-latest}
    build:
      context: ../../apps/proxy
      dockerfile: Dockerfile.ce
