name: Баг-репорт
description: Сообщите об ошибке, чтобы помочь нам улучшить Локсо
title: "🐛 Баг: "
labels: [🐛bug]
body:
- type: markdown
  attributes:
    value: |
      Спасибо, что нашли время заполнить этот баг-репорт.
- type: checkboxes
  attributes:
    label: Такой issue уже существует?
    description: Пожалуйста, проверьте, не создан ли уже issue с описанием этой ошибки
    options:
    - label: Я проверил(а) существующие issues
      required: true
- type: textarea
  attributes:
    label: Текущее поведение
    description: Кратко опишите, что происходит и что вы ожидаете увидеть
    placeholder: |
      Когда я делаю <X>, происходит <Y> и появляется следующее сообщение об ошибке:
      ```...```
      Я ожидаю, что произойдёт <Z>
  validations:
    required: true
- type: textarea
  attributes:
    label: Шаги для воспроизведения
    description: Опишите шаги для воспроизведения этого поведения, приложите логи консоли или сети и скриншоты
    placeholder: |
      1. Перейти в '...'
      2. Нажать на '....'
      3. Прокрутить вниз до '....'
      4. Увидеть ошибку
  validations:
    required: true
- type: dropdown
  id: env
  attributes:
    label: Окружение
    options:
      - Продакшн
  validations:
    required: true
- type: dropdown
  id: browser
  attributes:
    label: Браузер
    options:
      - Google Chrome
      - Mozilla Firefox
      - Safari
      - Другой
- type: dropdown
  id: variant
  attributes:
    label: Вариант установки
    options:
      - Облако
      - Self-hosted
      - Локально
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Версия
    placeholder: v1.3.1
  validations:
    required: true
