name: Запрос функции
description: Предложите функцию для улучшения Локсо
title: "🚀 Фича: "
labels: [✨feature]
body:
- type: markdown
  attributes:
    value: |
      Спасибо, что нашли время предложить новую функцию для Локсо
- type: checkboxes
  attributes:
    label: Такой issue уже существует?
    description: Пожалуйста, проверьте, не создан ли уже issue, связанный с этим запросом функции
    options:
    - label: Я проверил(а) существующие issues
      required: true
- type: textarea
  attributes:
    label: Описание
    description: Краткое описание функции в одном абзаце
  validations:
    required: true
- type: textarea
  attributes:
    label: Зачем это нужно?
    description: Кратко опишите проблемы или сценарии использования, которые решает этот запрос функции
  validations:
    required: true
