service: lokso-admin
image: abuhtoyarov/lokso-admin

servers:
  web:
    hosts:
      - 176.108.250.162

proxy:
  host: app.lokso.ru
  app_port: 3000
  path_prefix: /god-mode
  strip_path_prefix: false
  healthcheck:
    path: /
